name: voxin_control
description: VoxIN Control
publish_to: 'none'
version: 0.3.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
